language: c

git:
  depth: 5

addons:
  apt:
    packages:
    - libssl-dev
    - libevent-dev
    - libexpat-dev
    - clang
  homebrew:
    packages:
      - openssl
      - libevent
      - expat
    update: true

jobs:
  include:
    - os: linux
      name: Asan, GCC on Linux, Amd64
      compiler: gcc
      arch: amd64
      dist: bionic
      env:
        - TEST_ASAN=yes
    - os: linux
      name: Asan, GCC on Linux, Arm64
      compiler: gcc
      arch: arm64-graviton2
      virt: lxd
      group: edge
      dist: bionic
      env:
        - TEST_ASAN=yes

  allow_failures:
    - os: linux
      name: Android armv7a, Linux, Amd64
    - os: linux
      name: Android aarch64, Linux, Amd64
    - os: linux
      name: Android x86, Linux, Amd64
    - os: linux
      name: Android x86_64, Linux, Amd64

before_script:
  - |
    if [ "$TEST_ANDROID" = "yes" ]; then
      ./contrib/android/install_tools.sh
    fi
  - |
    if [ "$TEST_IOS" = "yes" ]; then
      ./contrib/ios/install_tools.sh
    fi

# The Travis docs say to avoid calling exit in the script. It leads to
# some code duplication to avoid failures in cross-compiles. Also see
# https://docs.travis-ci.com/user/job-lifecycle/ in the Travis docs.
script:
  - |
    if [ "$TEST_ASAN" = "yes" ]; then
      export CFLAGS="-DNDEBUG -g2 -O3 -fsanitize=address"
      ./configure
      make -j 2
      make test
    fi
